on:
    workflow_dispatch:
        inputs:
            run_workflow:
                description: Run the workflow
                type: boolean
  
name: Default Workflow
  
jobs:
  default:
    runs-on: ubuntu-latest
    name: Run Job
    steps:
        - run: echo ${{ inputs.run_workflow }}