on:
    workflow_run:
      workflows:
        - '**'
      types:
        - completed

name: Pipeline Monitoring
jobs:
    on-workflow-failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - name: Get workflow run jobs
          run: |
            # Fetching the jobs for the failed workflow run
            curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs > jobs.json
            
            # Extracting failed jobs
            failed_jobs=$(jq -r '.jobs[] | select(.conclusion=="failure") | .id' jobs.json)
            debug=$(jq -r '.jobs[] | select(.conclusion=="failure")' jobs.json)
            echo "Debug: \n $debug"
            for job_id in $failed_jobs; do
              echo "Job ID: $job_id failed."
              # Fetch steps for the failed job
              curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/jobs/$job_id | jq -r '.steps[] | select(.conclusion=="failure") | "\(.name) step failed with conclusion: \(.conclusion)"'
            done
  
  