on: [pull_request]

jobs:
    token:
        runs-on: ubuntu-latest
        outputs:
            bot-token: ${{ steps.token-output.outputs.bot-token }}
        steps:
          - uses: actions/create-github-app-token@v1
            id: app-token
            with:
              app-id: ${{ vars.APP_ID }}
              private-key: ${{ secrets.PRIVATE_KEY }}
          - id: token-output
            run: echo "bot-token=${{ steps.app-token.outputs.token }}" >> $GITHUB_ENV
    triage:
        name: Subject label
        runs-on: ubuntu-latest
        needs: [token]
        steps:
            - uses: actions/labeler@v3
              with:
                repo-token: ${{ needs.token.outputs.bot-token }}

    size-label:
        name: Size label
        runs-on: ubuntu-latest
        needs: [token]
        steps:
            - name: size-label
              uses: pascalgn/size-label-action@v0.4.3
              env:
                GITHUB_TOKEN: ${{ needs.token.outputs.bot-token }}
              with:
                sizes: >
                  {
                    "0": "XS",
                    "20": "S",
                    "50": "M",
                    "250": "L",
                    "500": "Too Large"
                  }

    comment:
        name: Make a PR Comment
        runs-on: ubuntu-latest
        needs: [token]
        steps:
            - name: pr-comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                issue-number: ${{ github.event.pull_request.number }}
                token: ${{ needs.token.outputs.bot-token }}
                body: "Im working!"
                