on: [pull_request]

jobs:
    size-label:
        name: Size label
        runs-on: ubuntu-latest
        steps:
          - uses: actions/create-github-app-token@v1
            id: app-token
            with:
              # required
              app-id: ${{ vars.APP_ID }}
              private-key: ${{ secrets.PRIVATE_KEY }}
          - name: size-label
            uses: pascalgn/size-label-action@v0.4.3
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
            with:
              sizes: >
                {
                  "0": "XS",
                  "20": "S",
                  "50": "M",
                  "250": "L",
                  "500": "Too Large"
                }

    comment:
        name: Make a PR Comment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                # required
                app-id: ${{ vars.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}
            - name: pr-comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                token: ${{ steps.app-token.outputs.token }}
                body: "Im working!"
                issue-number: ${{ github.event.pull_request.number }}

    # commit:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/create-github-app-token@v1
    #         id: app-token
    #         with:
    #           # required
    #           app-id: ${{ vars.APP_ID }}
    #           private-key: ${{ secrets.PRIVATE_KEY }}
    #       - uses: actions/checkout@v4
    #         with:
    #           token: ${{ steps.app-token.outputs.token }}
    #           ref: main
    #       - name: create file
    #         run: echo "Hello World" > hello.txt
    #       - name: Get GitHub App User ID
    #         id: get-user-id
    #         run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
    #         env:
    #           GH_TOKEN: ${{ steps.app-token.outputs.token }}
    #       - run: |
    #           git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
    #           git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
    #       # git commands like commit work using the bot user
    #       - run: |
    #           git add .
    #           git commit -m "Auto-generated changes"
    #           git push