on: [pull_request]

jobs:
    size-label:
        name: Size label
        runs-on: ubuntu-latest
        steps:
          - uses: actions/create-github-app-token@v1
            id: app-token
            with:
              # required
              app-id: ${{ vars.APP_ID }}
              private-key: ${{ secrets.PRIVATE_KEY }}
          - name: size-label
            uses: pascalgn/size-label-action@v0.4.3
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
            with:
              sizes: >
                {
                  "0": "XS",
                  "20": "S",
                  "50": "M",
                  "250": "L",
                  "500": "Too Large"
                }

    comment:
        name: Make a PR Comment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                # required
                app-id: ${{ vars.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}
            - name: pr-comment
              uses: peter-evans/create-or-update-comment@v3
              with:
                token: ${{ steps.app-token.outputs.token }}
                body: "Im working!"
                issue-number: ${{ github.event.pull_request.number }}