name: Scheduled Run

on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:
    inputs:
      test:
        description: Teste de Inputs no workflow dispatch
        type: boolean
        default: false

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Teste de Inputs
        run: echo '${{ fromJSON(github) }}''