name: Daily Build

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      test:
        description: Teste de Inputs no workflow dispatch
        type: boolean
        default: false

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Teste de Inputs
        run: echo "${{ fromJSON(github.event.inputs) }}"