on:
    workflow_run:
        workflows:
            - '**'
        types:
            - completed

name: Pipeline Monitoring

jobs:
    on-workflow:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ toJSON(github.event.workflow_run) }}
  