on:
    workflow_run:
        workflows:
            - '**'
        types:
            - completed

name: Pipeline Monitoring

jobs:
    on-workflow-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo ${{ toJSON(github.event.workflow_run) }}
  